### ISSUE TITLE
expired :(

### ISSUE THREAD

**Issue by l4ckyguy** [GetRektBoy724/MeterPwrShell#1]
wrong shc -e ?((

**Comment by GetRektBoy724** [comment]
ohh sorry i'll fix it now

**Comment by GetRektBoy724** [comment]
for what version?

**Comment by GetRektBoy724** [comment]
@l4ckyguy ?

**Comment by GetRektBoy724** [comment]
i already tested the executeable for v1.2.0 and there is no problem
closing this thread...
