### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 98Kstar** [GetRektBoy724/MeterPwrShell#10]
Reverse_tcp using msf can connect back, but cannot execute related commands

**Comment by GetRektBoy724** [comment]
pls elaborate and pls include `.debug.log` and `.ngrok.debug.log`(if exist).both of them are hidden file and located at the same directory with MeterPwrShell.

**Comment by GetRektBoy724** [comment]
7 day without response,closing this issue thread.
Reopen if you want to continue.
