### ISSUE TITLE
cant answer so fast, sorry ;)

### ISSUE THREAD

**Issue by l4ckyguy** [GetRektBoy724/MeterPwrShell#2]
❯ ./meterpwrshellexec 
./meterpwrshellexec: �ק�|f�J�Q�
                               �� �has expired!
Please contact your provider jahidulhamid@yahoo.com

**Comment by l4ckyguy** [comment]
check your date settings ;)

**Comment by GetRektBoy724** [comment]
ahh sorry yea its got error,i forgot `-r` on the shc

**Comment by GetRektBoy724** [comment]
now its fixed for v1.2.0
