### ISSUE TITLE
No Reverse Connection

### ISSUE THREAD

**Issue by hdhelix-jelly** [GetRektBoy724/MeterPwrShell#3]
Hey, 
Thanks for that tool. I just tried it, but no connection succeeded.
I tried it without NGrok, only in my local NW.

If i execute the output on my Windows Machine nothing happend.

Maybe i do something wrong.

THX

**Comment by GetRektBoy724** [comment]
hey,sorry for the late reply,thx for using the tool
can you post the `.debug.log` on here?
it should be on where you store the `meterpwrshellexec`
and also on the tool,it said that `The Payload Is Not Guaranteed To Work If You Dont Use Ngrok!!!`
so dont surprised if it doesnt work :D

**Comment by GetRektBoy724** [comment]
Hey,if you dont response again,probably im just going to close this issue.

**Comment by GetRektBoy724** [comment]
issue closed !
reason : didnt responds and provide more information
