### ISSUE TITLE
Path Question

### ISSUE THREAD

**Issue by xiaoheiccc** [GetRektBoy724/MeterPwrShell#4]
My ubuntubash path is not in /usr/bin/bash, but /bin/bash, but I cannot modify the path
![image](https://user-images.githubusercontent.com/49157802/116502443-126cd980-a8e6-11eb-875c-e6469239b65d.png)

**Comment by GetRektBoy724** [comment]
Ummm first, try run `ls -lah /bin` and post the output here.
normally `/bin` is symlinked to `/usr/bin`.
![image](https://user-images.githubusercontent.com/41237415/116544173-fb93aa80-a918-11eb-99af-17da9c5865de.png)
if you see right there,my `/bin` is symlinked to `/usr/bin`.
if it's not working out,pls be patient,I'm gonna release MeterPwrShell v2 ASAP

**Comment by xiaoheiccc** [comment]
First of all, thank you for your reply, but I didn't see / bin, so when will meterpwrshell V2 be released

**Comment by GetRektBoy724** [comment]
probably a week,im still testing out for the stability ;)

**Comment by GetRektBoy724** [comment]
MeterPwrShell2 Released!
Please download the binary on Release page according to your OS!
