### ISSUE TITLE
no reverse connection

### ISSUE THREAD

**Issue by pretech86** [GetRektBoy724/MeterPwrShell#5]
thanks for the great tool , really i appreciate you , but i face some issue 

1- every time it said cowsay not installed and install it every time 
2- every time it askabout metasploit path
3- my payload is windows/meterpreter/reverse_tcp
4- when i choosedthe payload iget this `[---] Checking Payload Availability . . . [---]
Traceback (most recent call last):
	4: from /usr/bin/msfvenom:414:in `<main>'
	3: from /usr/bin/msfvenom:414:in `each'
	2: from /usr/bin/msfvenom:417:in `block in <main>'
	1: from /usr/bin/msfvenom:417:in `puts'
/usr/bin/msfvenom:417:in `write': Broken pipe @ io_write - <STDOUT> (Errno::EPIPE)
 [---] Payload Available On Metasploit [---]
`
5- i didnt get any reverese connection 
6- i didnt find .debug.log in the same folder

**Comment by GetRektBoy724** [comment]
yes im trying to fix this on MeterPwrShell v2,pls be patient
i'll do more stability tests on MeterPwrShell v2

**Comment by GetRektBoy724** [comment]
for the number 2,its probably caused by wrong path

**Comment by GetRektBoy724** [comment]
and also if you post a stack trace,dont forget to encapsulate it with bacticks like 
```
[stack trace in here]
```

**Comment by GetRektBoy724** [comment]
MeterPwrShell2 Released!
Please download the binary on Release page according to your OS!
