### ISSUE TITLE
Probably architecture or OS problem

### ISSUE THREAD

**Issue by xiaoheiccc** [GetRektBoy724/MeterPwrShell#8]
Sorry, I don’t quite understand why it is like this after I run him
![image](https://user-images.githubusercontent.com/49157802/117596155-4c0ad380-b175-11eb-8dcd-a24d0588077c.png)

**Comment by GetRektBoy724** [comment]
what is your machine architecture?

**Comment by GetRektBoy724** [comment]
try run `dpkg --print-architecture` and paste the output here

**Comment by xiaoheiccc** [comment]
![image](https://user-images.githubusercontent.com/49157802/117641351-9feadc00-b1b8-11eb-892f-ab80b96e0f1f.png)
ummm

**Comment by GetRektBoy724** [comment]
im so sorry once again,pls retry to download the binary again.
i (should be) fixed it.pls tell me if it works :)
and also can i know what ubuntu you're using?

**Comment by xiaoheiccc** [comment]
Thank you very much, the problem is solved after re-downloading the binary file

**Comment by GetRektBoy724** [comment]
yea np.finally :D
